feat: updated PolygonParts examples and profile(MAPCO-5170)
MapColonies/developer-portal pull request #121
Opened 2024-11-11 09:21 UTC by RonitKissis

2024-11-11 18:32 UTC, shimoncohen requested changes

2024-11-12 08:02 UTC, RonitKissis commented on docs/MapColonies/Raster/services/PolygonParts/README.md
> +We got a `FeatureTypeList` consisting of the different `FeatureTypes` that each one hold and represent some catalog layer under the WFS service. one of them is the `polygonParts:ORTHOPHOTO_BEST-Ortho
yes. We updated the wfs layer in prod azure env and wanted to update all the requests and response according to it, to enable easy and smooth integration with getMap as requested in the ticket.

2024-11-12 08:11 UTC, RonitKissis commented on docs/MapColonies/Raster/services/PolygonParts/README.md
> +                "description": "תשתית אורתופוטו באיזור צפון עזה עדכנית לאוגוסט 2022"
This is the real data stored in the DB and represents the layer parts

2024-11-12 08:11 UTC, RonitKissis commented on docs/MapColonies/Raster/services/PolygonParts/README.md
> +                "description": "תשתית אורתופוטו באיו\"ש עדכני ליוני 2021"
Same here.

2024-11-12 08:12 UTC, RonitKissis commented on docs/MapColonies/Raster/services/PolygonParts/README.md
> +                "description": "תשתית אורתופוטו באיזור צפון עזה עדכנית לאוגוסט 2022"
Same here.

2024-11-12 08:12 UTC, RonitKissis commented on docs/MapColonies/Raster/services/PolygonParts/README.md
> +                "description": "תשתית אורתופוטו באיו\"ש עדכני ליוני 2021"
Same here.

2024-11-12 08:12 UTC, RonitKissis commented on docs/MapColonies/Raster/services/PolygonParts/README.md
> +                "description": "תשתית אורתופוטו באיו\"ש עדכני למאי 2021"
Same here.

2024-11-12 09:41 UTC, CL-SHLOMIKONCHA requested changes

2024-11-12 09:41 UTC, CL-SHLOMIKONCHA commented on docs/MapColonies/Raster/services/PolygonParts/README.md
>     the polygon is a list of latitude-longitude pair coordinates.
longitude-latitude

2024-11-12 09:43 UTC, CL-SHLOMIKONCHA commented
sensors responses includes regions names, please change to "OTHER" in all response examples

2024-11-12 09:44 UTC, CL-SHLOMIKONCHA commented
Please get rid of description in response examples, leave empty string

2024-11-12 12:17 UTC, CL-SHLOMIKONCHA approved these changes

2024-11-12 15:52 UTC, shimoncohen commented on docs/MapColonies/Raster/services/PolygonParts/README.md
>                  "countries": "עולמי",
Please change.

2024-11-12 16:04 UTC, shimoncohen approved these changes

2024-11-12 16:06 UTC, merged