chore: openlayers 6 api support
MapColonies/developer-portal pull request #48
Opened 2022-11-28 12:25 UTC by AnguIar

2022-11-28 12:54 UTC, asafMasa requested changes

2022-11-28 12:54 UTC, asafMasa commented on docs/getting-started/raster/raster_step-by-step.md
> +    const capabilitiesResponse = await fetch('<RASTER-RASTER-SERVING-SERVICE_URL>/wmts/1.0.0/WMTSCapabilities.xml');      // from Step_4
Why don't you use the build-in capabilities URL from links?

The following should be changed to 
<mc:links scheme="WMTS" name="[desired_layer_identifier]" description=""
url=[capabilities-url]>
</mc:links>
and then reference the link

2022-11-28 12:54 UTC, asafMasa commented on docs/getting-started/raster/raster_step-by-step.md
> +      layer: '<LAYER_NAME>'                                                                                               // from Step_3
<LAYER_NAME> -> [desired_layer_identifier] from links

2022-12-19 16:42 UTC, syncush requested changes
fix conflicts and rebase

2022-12-22 15:04 UTC, asafMasa requested changes

2022-12-22 15:04 UTC, asafMasa commented on docs/getting-started/raster/raster_step-by-step.md
> +- When fetching data, make sure to provide correct **WMTS Capabilities URL**
add extent of BBOX from CSW to layer

2022-12-22 15:04 UTC, asafMasa commented on docs/getting-started/raster/raster_step-by-step.md
> +- When fetching data, make sure to provide correct **WMTS Capabilities URL**
check if notes are needed (Capabilities, desired_layer_identifier)

2022-12-25 15:12 UTC, asafMasa approved these changes

2022-12-26 13:06 UTC, syncush approved these changes

2022-12-26 13:06 UTC, merged