docs: add DEM docs
MapColonies/developer-portal pull request #60
Opened 2023-08-28 12:05 UTC by shimoncohen

2023-08-28 12:26 UTC, alebinson submitted a review, later dismissed
looks good

2023-08-31 13:25 UTC, syncush requested changes

2023-09-04 06:08 UTC, shimoncohen commented on docs/MapColonies/DEM/Services/catalog/README.md
> +  - DEM
Added tags.

2023-09-04 06:08 UTC, shimoncohen commented on docs/MapColonies/DEM/Services/catalog/README.md
> +  - quantaized-mesh
Removed tags.

2023-09-04 06:09 UTC, shimoncohen commented on docs/MapColonies/DEM/Services/catalog/README.md
> +  - smart-reality
Removed tag.

2023-09-04 06:11 UTC, shimoncohen commented on docs/MapColonies/DEM/Services/data_coverage_service.md
> +
Removed file.

2023-09-04 06:13 UTC, shimoncohen commented on docs/MapColonies/DEM/Guides/DEM_getting_started.md
> +> **See the principles [here](/ogc-protocols/ogc-csw-auth.md)**
Fixed.

2023-09-04 06:48 UTC, shimoncohen commented on docs/MapColonies/DEM/Services/map_server.md
> +
Removed file.

2023-09-04 08:40 UTC, shimoncohen commented on docs/MapColonies/DEM/README.md
> +## DEM (DTM / DSM)  <!-- {docsify-ignore} -->
Removed.

2023-09-04 08:40 UTC, shimoncohen commented on docs/MapColonies/DEM/Services/map_server.md
> +
Removed file.

2023-09-04 09:23 UTC, shimoncohen commented on docs/MapColonies/DEM/README.md
> +* In **3D** view, the terrain surface is visualized in an oblique three-dimensional perspective, using raster tiles or TIN mesh tiles. It can be augmented with a satellite imagery to make it look rea
Added images.

2023-09-05 11:39 UTC, syncush approved these changes

2023-09-05 11:39 UTC, merged