Add Valhalla docs
MapColonies/developer-portal pull request #63
Opened 2023-09-28 10:33 UTC by shirCitron

2023-10-02 08:34 UTC, CptSchnitz requested changes
I think there are too many APIs and a lack of examples. we need to somehow make the docs more concise.

2023-10-02 08:34 UTC, CptSchnitz commented on docs/MapColonies/vector/Services/valhalla_service.md
1. The order of the page could be better. it should be about selling the service so terminology should not be first (maybe even on a separate page).
2. The page is missing some pictures to sell the service.

2023-10-02 08:34 UTC, CptSchnitz commented on docs/MapColonies/vector/Services/valhalla_service.md
> +    #### "I am trying to run more than one errand in the day or start my own delivery service!" 🤷
why is there a title in the middle of a bulleted list?
![image](https://github.com/MapColonies/developer-portal/assets/12687466/fb6451d5-6c48-47ec-9f9d-6e317113135b)

2023-10-02 08:34 UTC, CptSchnitz commented on docs/MapColonies/openstreetmap/valhalla/turn-by-turn/api-reference.md
> +|599 | Unknown |
should not be part of the developer portal

2023-10-02 08:34 UTC, CptSchnitz commented on docs/MapColonies/openstreetmap/valhalla/turn-by-turn/api-reference.md
something is bad in the title hierarchy. i don't think `Directions options` should be under `Costing models`.

2023-10-26 12:41 UTC, CptSchnitz requested changes

2023-10-26 12:41 UTC, CptSchnitz commented on docs/MapColonies/vector/Services/valhalla_service.md
>  * **centroid** - allows you to find the least cost convergence point of routes from multiple locations.
if we have no documentation about it, just remove the line.

2023-10-30 15:40 UTC, shimoncohen commented
Please move all of `OPenStreetMap` under `Knowledge base` under `Vector`.
In addition, I think we should move all of the API's to be under the service description, what do you think?

2023-10-31 08:50 UTC, shirCitron commented
>

2023-11-04 21:05 UTC, shimoncohen requested changes

2023-11-04 21:05 UTC, shimoncohen commented on docs/MapColonies/openstreetmap/valhalla/turn-by-turn/overview.md
> +![Routing settings](../../../../../static/img/openstreetmap/valhalla/routing-transport.png)
Did you mean to write `Routing transport`?

2023-11-04 21:05 UTC, shimoncohen commented on docs/MapColonies/openstreetmap/valhalla/turn-by-turn/overview.md
> +![Routing settings](../../../../../static/img/openstreetmap/valhalla/route-example.png)
Did you mean to write `Route example`?

2023-11-04 21:05 UTC, shimoncohen commented on docs/MapColonies/vector/Services/valhalla_service.md
> +Valhalla is an open source routing engine and accompanying libraries for use with OpenStreetMap data. Valhalla also includes tools like time+distance matrix computation, isochrones, elevation samplin
We should add a link to the `Valhalla` docs and website to credit them.
Same for `Nominatim`.

2023-11-09 13:33 UTC, shimoncohen approved these changes

2023-11-09 13:36 UTC, shimoncohen submitted a review, later dismissed

2023-11-12 08:50 UTC, CptSchnitz approved these changes

2023-12-13 18:53 UTC, merged